/**
 * The pages this site generates rather than writes: the backlog, one page per
 * User Story, the badges index and one page per badge holder.
 *
 * They are built here, once, and called with the words of a locale, so the
 * French backlog cannot drift from the English one: what differs between them
 * is i18n/<locale>.json and nothing else. scripts/build/universe.mjs builds the
 * repository's BACKLOG.md from these, and scripts/build/site.mjs builds the site
 * pages of every locale.
 *
 * Every builder returns markdown without front matter. The caller adds it,
 * because the title, the description and the alternates depend on where the page
 * is published.
 */
import { fill } from "./strings.mjs";

const separator = (columns) => `|${columns.map(() => "---").join("|")}|`;
const row = (cells) => `| ${cells.join(" | ")} |`;

/**
 * The backlog: the table of the stories, each one in full, and the team.
 *
 * storyLink is what a story id points at, which is the site page on the
 * repository copy and the neighbouring file on the site.
 */
export function backlogPage({ universe, s, text, storyLink, generatedBy }) {
  const lines = [];
  if (generatedBy) {
    lines.push(`<!-- Generated by ${generatedBy}. Do not edit by hand. -->`, "");
  }
  lines.push(`# ${s.backlog.heading}`, "", text.pitch(), "", ...s.backlog.intro, "");
  lines.push(row(s.backlog.columns), separator(s.backlog.columns));
  for (const story of universe.userStories) {
    const owner = universe.cast.find((person) => person.handle === story.author);
    const one = text.story(story);
    lines.push(row([
      `[${story.id}](${storyLink(story)})`,
      story.level,
      one.title,
      owner ? text.name(owner) : story.author,
      `\`${story.branch}\``
    ]));
  }
  lines.push("", `## ${s.backlog.inFull}`, "");
  for (const story of universe.userStories) {
    const owner = universe.cast.find((person) => person.handle === story.author);
    const one = text.story(story);
    // Kept for the links written before each story had its own page
    lines.push(`<a id="${story.id}"></a>`, "", `### ${story.id} - ${one.title}`, "");
    lines.push(`**${s.backlog.owner}**: ${owner ? text.name(owner) : story.author}  `);
    lines.push(`**${s.backlog.branch}**: \`${story.branch}\`  `);
    lines.push(`**${s.backlog.lab}**: ${story.level}.${story.lab}`, "");
    lines.push(`> ${one.story}`, "");
    lines.push(s.backlog.acceptance, "");
    for (const criterion of one.acceptance) {
      lines.push(`- ${criterion}`);
    }
    lines.push("");
  }
  lines.push(`## ${s.backlog.team}`, "");
  lines.push(row(s.backlog.teamColumns), separator(s.backlog.teamColumns));
  for (const person of universe.cast) {
    lines.push(row([text.name(person), text.role(person)]));
  }
  lines.push("");
  return lines.join("\n");
}

/**
 * One story page, which is where a ticket link lands: the configuration of the
 * course builds its URL from the id alone.
 */
export function storyPage({ universe, s, text, story, owner, labLink, backlogLink }) {
  const one = text.story(story);
  return [
    `# ${story.id} - ${one.title}`,
    "",
    `> ${one.story}`,
    "",
    s.story.acceptance,
    "",
    ...one.acceptance.map((criterion) => `- ${criterion}`),
    "",
    "| | |",
    "|---|---|",
    row([s.story.owner, owner ? text.name(owner) : story.author]),
    row([s.story.branch, `\`${story.branch}\``]),
    row([s.story.deliveredIn, labLink]),
    "",
    `[${s.story.backToBacklog}](${backlogLink})`,
    ""
  ].join("\n");
}

/** The badges index: everybody who claimed one, and how to claim yours. */
export function badgesPage({ s, holders, badgeHref, badgeImage, claimUrl, recordUrlPattern }) {
  const rows = holders.map((holder) => {
    // An <img> and not markdown: the badge is drawn 320 square, and a table cell
    // wants a thumbnail. Plain HTML sizes it without depending on an extension.
    const image = holder.highest
      ? `<img src="${badgeImage(holder.key, holder.highest.level)}" alt="${holder.highest.name}" width="72"/>`
      : "";
    const trailblazer = holder.trailblazer
      ? `[${holder.trailblazer}](https://www.salesforce.com/trailblazer/${holder.trailblazer})`
      : "";
    const github = holder.recipient ? `[@${holder.recipient}](https://github.com/${holder.recipient})` : "";
    return row([image, `[${holder.name}](${badgeHref(holder.key)})`, holder.highest ? holder.highest.name : "", github, trailblazer]);
  });

  return [
    `# ${s.badges.heading}`,
    "",
    ...s.badges.intro,
    "",
    holders.length === 0 ? s.badges.nobody : [row(s.badges.columns), separator(s.badges.columns), ...rows].join("\n"),
    "",
    `## ${s.badges.claim.heading}`,
    "",
    ...s.badges.claim.body.map((line) => fill(line, { claimUrl })),
    "",
    `## ${s.badges.readFromElsewhere.heading}`,
    "",
    ...s.badges.readFromElsewhere.intro,
    "",
    "```",
    recordUrlPattern,
    "```",
    "",
    ...s.badges.readFromElsewhere.outro,
    ""
  ].join("\n");
}

/**
 * One badge holder's page, from the record the claim wrote.
 *
 * The record is the source: the page is built from it on every site build, in
 * every language, so a claim never has to write a page per locale and an old
 * badge gains the new languages by itself.
 */
export function badgePage({ s, record, badgeImage, courseUrl }) {
  const badges = record.badges || [];
  const rows = badges.map((badge) => row([
    `![${badge.name}](${badgeImage(badge.level)})`,
    `**${badge.name}**`,
    badge.issuedOn,
    fill(s.badge.checks, { passed: badge.checksPassed, total: badge.checksTotal })
  ]));
  const evidence = badges[0] && badges[0].evidence && badges[0].evidence[0];
  const repository = evidence && evidence.url
    ? `[${s.badge.meaning.repository}](${evidence.url})`
    : s.badge.meaning.fallbackRepository;

  return [
    `# ${fill(s.badge.heading, { name: record.name })}`,
    "",
    `${s.badge.github}: [@${record.recipient}](https://github.com/${record.recipient})`,
    record.trailblazer
      ? `<br/>${s.badge.trailblazer}: [${record.trailblazer}](https://www.salesforce.com/trailblazer/${record.trailblazer})`
      : "",
    "",
    row(s.badge.columns),
    separator(s.badge.columns),
    ...rows,
    "",
    `## ${s.badge.meaning.heading}`,
    "",
    ...s.badge.meaning.body.map((line) => fill(line, { repository })),
    "",
    `## ${s.badge.notCertification.heading}`,
    "",
    ...s.badge.notCertification.body,
    "",
    `[${s.badge.takeTheCourse}](${courseUrl}){ .md-button }`,
    ""
  ].join("\n");
}
